DRYD-943: Add Transport Procedure
collectionspace/cspace-ui.js pull request #127
Opened 2021-02-19 00:21 UTC by mikejritter

Resolves: https://collectionspace.atlassian.net/browse/DRYD-943

* Adds ui components for transport procedure

Note: I wasn't really sure what to do for the title, so I only used the `transportReferenceNumber`.

2021-03-13 02:10 UTC, ray-lee requested changes
Mike, this looks good. Just a couple comments. Thanks!

2021-03-13 02:10 UTC, ray-lee commented on src/plugins/recordTypes/transport/optionLists.js
> +        defaultMessage: 'lofo freight',
It looks like "LOFO" is normally all caps... let's go with that.

2021-03-13 02:10 UTC, ray-lee commented on src/plugins/recordTypes/transport/optionLists.js
> +    ],
For static option lists, the best practice is to make the data values identical to the default message string, including case. That way you get exactly the same value if you're querying the database or REST API as you do in the UI, as long as you haven't overridden the default message. So it's best to lowercase all the above values (except for "LOFO freight" -- see comment below).

2021-03-15 17:36 UTC, mikejritter commented on src/plugins/recordTypes/transport/fields.js
> +            dataType: DATA_TYPE_FLOAT,
It looks like I missed the `DATA_TYPE_INT` in general - certainly would make more sense for this field. Looking back at the changes I made to the application I used `datatype=float` as well in `base-procedure-transport.xml`. Do you want me to push an update to update it there as well?

2021-03-20 01:58 UTC, ray-lee commented on src/plugins/recordTypes/transport/fields.js
> +            dataType: DATA_TYPE_FLOAT,
Oh, I missed that too. Don't worry about it, I'll change it while I'm in there.

2021-03-20 03:14 UTC, merged