Add TimeBasedMedia fields
collectionspace/cspace-ui.js pull request #147
Opened 2022-05-03 22:14 UTC by mikejritter

Add fields and layout defined in:
* https://collectionspace.atlassian.net/browse/DRYD-1034
* https://collectionspace.atlassian.net/browse/DRYD-1039
* https://collectionspace.atlassian.net/browse/DRYD-1040
* https://collectionspace.atlassian.net/browse/DRYD-1041

2022-05-06 03:38 UTC, ray-lee requested changes
This is mostly good, but the main thing is missing `fullName` messages, and redundant `name` messages. A couple tips:
- Review the [style guide](https://github.com/collectionspace/cspace-ui.js/blob/master/docs/style/README.md).
- When testing your changes, look at what happens on the Search page. Select the record type you're working on, and click the **+ Field** button to add a field to search. If anything in the field selection dropdown is ambiguous, you likely need to add `fullName` messages to disambiguate. For example, the "Version" fields here:
![search_fields](https://user-images.githubusercontent.com/1395885/167062799-2f573e77-080a-410b-84d8-09a8f47cb522.png)
Conventionally, fields in a group should be grouped together in that dropdown, meaning that their `fullName` messages should all start with the same prefix. The convention is that the `fullName` of a field in a group is the `name` of the group + the `name` of the field.

2022-05-06 18:35 UTC, mikejritter commented on src/plugins/recordTypes/collectionobject/fields.js
> +              repeating: false,
@ray-lee  Looking back at the specs, the way it's formatted in the spreadsheet made me think it was supposed to be a group, but the wireframes didn't show them as being repeatable. Probably something to confirm with Megan about.

I also just saw that a few fields (`audioType`, `audioPreferences`, `audioSpecificationNotes`) are marked as being repeatable in the spreadsheet as well... maybe I should update everything to match the wireframes instead.

2022-05-11 22:44 UTC, mikejritter commented on src/plugins/recordTypes/collectionobject/fields.js
> +              repeating: false,
Updated to be repeating

2022-05-11 22:44 UTC, mikejritter commented on src/plugins/recordTypes/collectionobject/fields.js
> +              repeating: false,
Updated to be repeating

2022-05-13 21:41 UTC, ray-lee commented
This looks good. I didn't test the full functionality, but that can be done when it's deployed to dev.

2022-05-13 21:47 UTC, merged