DRYD-1286: Associated authorities
collectionspace/cspace-ui.js pull request #194
Opened 2023-10-24 19:14 UTC by mikejritter

**What does this do?**
This adds the associated authorities block to chronology, person, and place authorities.

**Why are we doing this? (with JIRA link)**
Jira: https://collectionspace.atlassian.net/browse/DRYD-1286

The associated authorities were mostly complete for 7.2 but changes were held off for the release. This adds them to the three authorities listed above.

**How should this be tested? Do these changes have associated tests?**
Along with the cspace application PR:

* Rebuild collectionspace so that the associated authorities block is included in chronology, person, and place
* Create a chronology, place, and person
  * When creating add an associated authority
  * Verify that the authority saves and reloads correctly  

**Dependencies for merging? Releasing to production?**
I chose to reuse an existing vocab, `relationtype`. This was previously only used by the citation authority but felt like a good fit for use here as well. 

**Has the application documentation been updated for these changes?**
No

**Did someone actually run this code to verify it works?**
@mikejritter tested locally

2024-01-13 01:56 UTC, ray-lee requested changes
A couple little things below. Also I noticed that in the Associated Authorities section, the field groups are labeled "Person", "People", "Organization", etc., and then "Related chronology". Is there a reason it has "Related" in that one, but not the others? It sticks out as being inconsistent.

2024-01-13 01:56 UTC, ray-lee commented on src/plugins/recordTypes/person/messages.js
> +      id: 'panel.chronology.authorities',
Should be `person` instead of `chronology`.

2024-01-13 01:56 UTC, ray-lee commented on src/plugins/recordTypes/place/messages.js
> +      id: 'panel.chronology.authorities',
Should be `place` instead of `chronology`.

2024-01-16 19:26 UTC, mikejritter commented
> Also I noticed that in the Associated Authorities section, the field groups are labeled "Person", "People", "Organization", etc., and then "Related chronology". Is there a reason it has "Related" in that one, but not the others? It sticks out as being inconsistent.

Looking at the ticket it seems like I missed the change for Chronology. It should use `Event/Era` based on the wireframe.

2024-01-17 19:52 UTC, mikejritter commented
@ray-lee this is now updated for the changes you requested as well as updating the layout to allow the note field to be multiline.

2024-01-18 20:58 UTC, ray-lee approved these changes
Looks good.

2024-01-18 20:58 UTC, merged