DRYD-1331: NAGPRA Inventory
collectionspace/cspace-ui.js pull request #217
Opened 2024-05-24 19:37 UTC by mikejritter

**What does this do?**
* Create nagprainventory procedure 

**Why are we doing this? (with JIRA link)**
Jira: https://collectionspace.atlassian.net/browse/DRYD-1331

**How should this be tested? Do these changes have associated tests?**
* Run `npm run test` and `npm run lint` as a sanity check
* Build collectionspace with the application pr for nagpra inventory and all tenants needed for running the integration tests
* Start collectionspace 
* Run the devserver
* Run basic operations for a procedure, e.g. 
  * Create a nagpra inventory
  * Search for a nagpra inventory (checking that advanced field search terms are consistent)
  * Relate nagpra inventories   

**Dependencies for merging? Releasing to production?**
None

**Has the application documentation been updated for these changes?**
No

**Did someone actually run this code to verify it works?**
@mikejritter tested locally

2024-05-28 22:21 UTC, mikejritter commented on src/plugins/recordTypes/nagprainventory/fields.js
> +            determinedBy: {
This needs to be updated to be repeatable to be in line with the spec. Likely also needs to be fixed in duty of care.

2024-06-04 00:39 UTC, ray-lee requested changes

2024-06-04 00:39 UTC, ray-lee commented on src/plugins/recordTypes/nagprainventory/fields.js
> +                defaultMessage: 'Inventory/Documentation Number',
Need sentence case on this, so 'Inventory/documentation number'.

2024-06-04 00:39 UTC, ray-lee commented on src/plugins/recordTypes/nagprainventory/fields.js
> +                defaultMessage: 'Origination Date',
Sentence case please.

2024-06-05 00:52 UTC, ray-lee approved these changes
Looks good.

2024-06-05 00:53 UTC, merged