DRYD-1358: Update Held-in-Trust
collectionspace/cspace-ui.js pull request #221
Opened 2024-06-12 20:10 UTC by mikejritter

**What does this do?**
* Update Held-in-Trust for NAGPRA workflows

**Why are we doing this? (with JIRA link)**
Jira: https://collectionspace.atlassian.net/browse/DRYD-1358

This updates the Held-in-Trust procedure which was going to be added for 8.0 to be compatible with NAGPRA related workflows. It 

**How should this be tested? Do these changes have associated tests?**
* Run `npm run lint` and `npm run tests`
* Rebuild collectionspace with the core tenant enabled
* Start collectionspace
* Start the devserver `npm run devserver`
* Check that the Held-in-Trust procedure saves and loads as expected
  * With the exception of heldintrust type which needs default terms
* Optionally check the messages in the advanced search

**Dependencies for merging? Releasing to production?**
None

**Has the application documentation been updated for these changes?**
No

**Did someone actually run this code to verify it works?**
@mikejritter tested against a local instance

2024-06-14 15:25 UTC, ray-lee requested changes

2024-06-14 15:25 UTC, ray-lee commented on src/plugins/recordTypes/heldintrust/fields.js
> +              type: AutocompleteInput,
Looks like this should be TermPickerInput.

2024-06-14 15:25 UTC, ray-lee commented on src/plugins/recordTypes/heldintrust/fields.js
Should we add the unique identification number validator to this? I think that didn't exist when this was originally implemented.

2024-06-14 19:37 UTC, mikejritter commented on src/plugins/recordTypes/heldintrust/fields.js
Oh good call, I overlooked that when bringing in Held-in-Trust previously.

2024-06-18 16:07 UTC, ray-lee approved these changes
Looks good!

2024-06-18 16:08 UTC, merged